
user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

doto:
    resource: "@DotoBundle/Resources/config/routing.yml"
    prefix: /

fp_openid_security:
    resource: "@FpOpenIdBundle/Resources/config/routing/security.xml"