security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
        
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false
        
        main:
            pattern: ^/
            form_login:
                default_target_path: /home
                login_path: /
                provider: fos_userbundle
                csrf_provider: security.csrf.token_manager 
            logout:       true
            anonymous:    true
            

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    access_control:
        - { path: ^/home, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        