# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value


services:
    user.openid_user_manager:
        class: UserBundle\Security\User\OpenIdUserManager
        # we used an EntityManager, so don't forget it in dependency injection
        # you may want to adapt it, only the IdentityManager is mandatory
        arguments: [@fp_openid.identity_manager, @doctrine.orm.entity_manager]